// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertChannelRuleEdit = `-- name: InsertChannelRuleEdit :one
INSERT INTO channel_rule_edits (channel, title_max_length, required_attributes, banned_words, edited_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertChannelRuleEditParams struct {
	Channel            string   `json:"channel"`
	TitleMaxLength     int32    `json:"title_max_length"`
	RequiredAttributes []string `json:"required_attributes"`
	BannedWords        []string `json:"banned_words"`
	EditedBy           int64    `json:"edited_by"`
}

type InsertChannelRuleEditRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertChannelRuleEdit(ctx context.Context, arg InsertChannelRuleEditParams) (InsertChannelRuleEditRow, error) {
	row := q.db.QueryRow(ctx, insertChannelRuleEdit,
		arg.Channel,
		arg.TitleMaxLength,
		arg.RequiredAttributes,
		arg.BannedWords,
		arg.EditedBy,
	)
	var i InsertChannelRuleEditRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const latestChannelRuleEdits = `-- name: LatestChannelRuleEdits :many
SELECT DISTINCT ON (e.channel) e.channel, e.title_max_length, e.required_attributes, e.banned_words,
       u.email AS edited_by, e.created_at
FROM channel_rule_edits e
JOIN users u ON u.id = e.edited_by
ORDER BY e.channel, e.id DESC
`

type LatestChannelRuleEditsRow struct {
	Channel            string             `json:"channel"`
	TitleMaxLength     int32              `json:"title_max_length"`
	RequiredAttributes []string           `json:"required_attributes"`
	BannedWords        []string           `json:"banned_words"`
	EditedBy           string             `json:"edited_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestChannelRuleEdits(ctx context.Context) ([]LatestChannelRuleEditsRow, error) {
	rows, err := q.db.Query(ctx, latestChannelRuleEdits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestChannelRuleEditsRow
	for rows.Next() {
		var i LatestChannelRuleEditsRow
		if err := rows.Scan(
			&i.Channel,
			&i.TitleMaxLength,
			&i.RequiredAttributes,
			&i.BannedWords,
			&i.EditedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
