// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBudgetBlock = `-- name: ClearBudgetBlock :exec
UPDATE budget SET blocked_at = NULL, limit_micro_usd = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) ClearBudgetBlock(ctx context.Context, limitMicroUsd int64) error {
	_, err := q.db.Exec(ctx, clearBudgetBlock, limitMicroUsd)
	return err
}

const finishCall = `-- name: FinishCall :exec
UPDATE ai_calls
SET status = $2, cost_micro_usd = $3, input_tokens = $4,
    output_tokens = $5, provider_generation_id = $6,
    error = $7, updated_at = now()
WHERE id = $1
`

type FinishCallParams struct {
	ID                   int64        `json:"id"`
	Status               AiCallStatus `json:"status"`
	CostMicroUsd         pgtype.Int8  `json:"cost_micro_usd"`
	InputTokens          pgtype.Int4  `json:"input_tokens"`
	OutputTokens         pgtype.Int4  `json:"output_tokens"`
	ProviderGenerationID pgtype.Text  `json:"provider_generation_id"`
	Error                pgtype.Text  `json:"error"`
}

func (q *Queries) FinishCall(ctx context.Context, arg FinishCallParams) error {
	_, err := q.db.Exec(ctx, finishCall,
		arg.ID,
		arg.Status,
		arg.CostMicroUsd,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ProviderGenerationID,
		arg.Error,
	)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT b.limit_micro_usd, b.blocked_at,
       coalesce((SELECT sum(spend_micro_usd) FROM ai_call_spend), 0)::bigint AS spent_micro_usd
FROM budget b WHERE b.id = 1
`

type GetBudgetRow struct {
	LimitMicroUsd int64              `json:"limit_micro_usd"`
	BlockedAt     pgtype.Timestamptz `json:"blocked_at"`
	SpentMicroUsd int64              `json:"spent_micro_usd"`
}

func (q *Queries) GetBudget(ctx context.Context) (GetBudgetRow, error) {
	row := q.db.QueryRow(ctx, getBudget)
	var i GetBudgetRow
	err := row.Scan(&i.LimitMicroUsd, &i.BlockedAt, &i.SpentMicroUsd)
	return i, err
}

const lockBudget = `-- name: LockBudget :one
SELECT limit_micro_usd, blocked_at FROM budget WHERE id = 1 FOR UPDATE
`

type LockBudgetRow struct {
	LimitMicroUsd int64              `json:"limit_micro_usd"`
	BlockedAt     pgtype.Timestamptz `json:"blocked_at"`
}

func (q *Queries) LockBudget(ctx context.Context) (LockBudgetRow, error) {
	row := q.db.QueryRow(ctx, lockBudget)
	var i LockBudgetRow
	err := row.Scan(&i.LimitMicroUsd, &i.BlockedAt)
	return i, err
}

const reserveCall = `-- name: ReserveCall :one
INSERT INTO ai_calls (job_id, product_id, purpose, model, prompt_template_id, prompt, reserved_micro_usd)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type ReserveCallParams struct {
	JobID            pgtype.Int8   `json:"job_id"`
	ProductID        pgtype.Int8   `json:"product_id"`
	Purpose          AiCallPurpose `json:"purpose"`
	Model            string        `json:"model"`
	PromptTemplateID string        `json:"prompt_template_id"`
	Prompt           string        `json:"prompt"`
	ReservedMicroUsd int64         `json:"reserved_micro_usd"`
}

func (q *Queries) ReserveCall(ctx context.Context, arg ReserveCallParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveCall,
		arg.JobID,
		arg.ProductID,
		arg.Purpose,
		arg.Model,
		arg.PromptTemplateID,
		arg.Prompt,
		arg.ReservedMicroUsd,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setBudgetBlocked = `-- name: SetBudgetBlocked :exec
UPDATE budget SET blocked_at = now(), updated_at = now() WHERE id = 1 AND blocked_at IS NULL
`

func (q *Queries) SetBudgetBlocked(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setBudgetBlocked)
	return err
}

const sweepReservations = `-- name: SweepReservations :execrows
UPDATE ai_calls SET status = 'possibly_charged', updated_at = now()
WHERE status = 'reserved' AND created_at < now() - make_interval(secs => $1::int)
`

func (q *Queries) SweepReservations(ctx context.Context, olderThanSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepReservations, olderThanSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const totalSpend = `-- name: TotalSpend :one
SELECT coalesce(sum(spend_micro_usd), 0)::bigint FROM ai_call_spend
`

func (q *Queries) TotalSpend(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalSpend)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
