// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvalCounts = `-- name: ApprovalCounts :many
SELECT l.channel,
       count(*)::int AS total,
       count(*) FILTER (WHERE EXISTS (
         SELECT 1 FROM approvals a WHERE a.listing_id = l.id AND a.listing_version = l.version
       ))::int AS approved
FROM listings l
JOIN products p ON p.id = l.product_id
WHERE ($1::bigint IS NULL OR p.upload_id = $1)
GROUP BY l.channel
ORDER BY l.channel
`

type ApprovalCountsRow struct {
	Channel  string `json:"channel"`
	Total    int32  `json:"total"`
	Approved int32  `json:"approved"`
}

func (q *Queries) ApprovalCounts(ctx context.Context, uploadID pgtype.Int8) ([]ApprovalCountsRow, error) {
	rows, err := q.db.Query(ctx, approvalCounts, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalCountsRow
	for rows.Next() {
		var i ApprovalCountsRow
		if err := rows.Scan(&i.Channel, &i.Total, &i.Approved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const approvedForChannel = `-- name: ApprovedForChannel :many
SELECT p.sku, l.title, l.bullet_1, l.bullet_2, l.bullet_3, l.bullet_4, l.bullet_5, l.description,
       pa.colour, pa.pattern, pa.sleeve, pa.neckline, pa.fit
FROM listings l
JOIN products p ON p.id = l.product_id
LEFT JOIN product_attributes pa ON pa.product_id = l.product_id
WHERE l.channel = $1 AND l.status = 'generated'
  AND ($2::bigint IS NULL OR p.upload_id = $2)
  AND EXISTS (SELECT 1 FROM approvals a WHERE a.listing_id = l.id AND a.listing_version = l.version)
ORDER BY lower(p.sku)
`

type ApprovedForChannelParams struct {
	Channel  string      `json:"channel"`
	UploadID pgtype.Int8 `json:"upload_id"`
}

type ApprovedForChannelRow struct {
	Sku         string      `json:"sku"`
	Title       pgtype.Text `json:"title"`
	Bullet1     pgtype.Text `json:"bullet_1"`
	Bullet2     pgtype.Text `json:"bullet_2"`
	Bullet3     pgtype.Text `json:"bullet_3"`
	Bullet4     pgtype.Text `json:"bullet_4"`
	Bullet5     pgtype.Text `json:"bullet_5"`
	Description pgtype.Text `json:"description"`
	Colour      pgtype.Text `json:"colour"`
	Pattern     pgtype.Text `json:"pattern"`
	Sleeve      pgtype.Text `json:"sleeve"`
	Neckline    pgtype.Text `json:"neckline"`
	Fit         pgtype.Text `json:"fit"`
}

func (q *Queries) ApprovedForChannel(ctx context.Context, arg ApprovedForChannelParams) ([]ApprovedForChannelRow, error) {
	rows, err := q.db.Query(ctx, approvedForChannel, arg.Channel, arg.UploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovedForChannelRow
	for rows.Next() {
		var i ApprovedForChannelRow
		if err := rows.Scan(
			&i.Sku,
			&i.Title,
			&i.Bullet1,
			&i.Bullet2,
			&i.Bullet3,
			&i.Bullet4,
			&i.Bullet5,
			&i.Description,
			&i.Colour,
			&i.Pattern,
			&i.Sleeve,
			&i.Neckline,
			&i.Fit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createExport = `-- name: CreateExport :one
INSERT INTO exports (created_by, upload_id) VALUES ($1, $2) RETURNING id, created_at
`

type CreateExportParams struct {
	CreatedBy int64       `json:"created_by"`
	UploadID  pgtype.Int8 `json:"upload_id"`
}

type CreateExportRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (CreateExportRow, error) {
	row := q.db.QueryRow(ctx, createExport, arg.CreatedBy, arg.UploadID)
	var i CreateExportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getExport = `-- name: GetExport :one
SELECT e.id, e.created_at, e.sent_at, u.email AS sent_by_email
FROM exports e LEFT JOIN users u ON u.id = e.sent_by
WHERE e.id = $1
`

type GetExportRow struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	SentByEmail pgtype.Text        `json:"sent_by_email"`
}

func (q *Queries) GetExport(ctx context.Context, id int64) (GetExportRow, error) {
	row := q.db.QueryRow(ctx, getExport, id)
	var i GetExportRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentByEmail,
	)
	return i, err
}

const getExportFile = `-- name: GetExportFile :one
SELECT file_path FROM export_files WHERE export_id = $1 AND channel = $2
`

type GetExportFileParams struct {
	ExportID int64  `json:"export_id"`
	Channel  string `json:"channel"`
}

func (q *Queries) GetExportFile(ctx context.Context, arg GetExportFileParams) (string, error) {
	row := q.db.QueryRow(ctx, getExportFile, arg.ExportID, arg.Channel)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const insertExportFile = `-- name: InsertExportFile :exec
INSERT INTO export_files (export_id, channel, file_path, row_count) VALUES ($1, $2, $3, $4)
`

type InsertExportFileParams struct {
	ExportID int64  `json:"export_id"`
	Channel  string `json:"channel"`
	FilePath string `json:"file_path"`
	RowCount int32  `json:"row_count"`
}

func (q *Queries) InsertExportFile(ctx context.Context, arg InsertExportFileParams) error {
	_, err := q.db.Exec(ctx, insertExportFile,
		arg.ExportID,
		arg.Channel,
		arg.FilePath,
		arg.RowCount,
	)
	return err
}

const listExportFiles = `-- name: ListExportFiles :many
SELECT channel, file_path, row_count FROM export_files WHERE export_id = $1 ORDER BY channel
`

type ListExportFilesRow struct {
	Channel  string `json:"channel"`
	FilePath string `json:"file_path"`
	RowCount int32  `json:"row_count"`
}

func (q *Queries) ListExportFiles(ctx context.Context, exportID int64) ([]ListExportFilesRow, error) {
	rows, err := q.db.Query(ctx, listExportFiles, exportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportFilesRow
	for rows.Next() {
		var i ListExportFilesRow
		if err := rows.Scan(&i.Channel, &i.FilePath, &i.RowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExports = `-- name: ListExports :many
SELECT e.id, e.created_at, e.sent_at, u.email AS sent_by_email
FROM exports e LEFT JOIN users u ON u.id = e.sent_by
WHERE (NOT $1::boolean OR e.sent_at IS NOT NULL)
  AND ($2::bigint IS NULL OR e.upload_id = $2)
  AND ($3::bigint = 0 OR e.id < $3)
ORDER BY e.id DESC
LIMIT $4
`

type ListExportsParams struct {
	SentOnly bool        `json:"sent_only"`
	UploadID pgtype.Int8 `json:"upload_id"`
	BeforeID int64       `json:"before_id"`
	PageSize int32       `json:"page_size"`
}

type ListExportsRow struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	SentByEmail pgtype.Text        `json:"sent_by_email"`
}

// Newest export first; sent_only limits it to what reviewers sent the seller.
func (q *Queries) ListExports(ctx context.Context, arg ListExportsParams) ([]ListExportsRow, error) {
	rows, err := q.db.Query(ctx, listExports,
		arg.SentOnly,
		arg.UploadID,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportsRow
	for rows.Next() {
		var i ListExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendExport = `-- name: SendExport :execrows
UPDATE exports SET sent_at = now(), sent_by = $1
WHERE id = $2 AND sent_at IS NULL
`

type SendExportParams struct {
	SentBy pgtype.Int8 `json:"sent_by"`
	ID     int64       `json:"id"`
}

// Sends once: a second send changes nothing, so the first sender and time stay.
func (q *Queries) SendExport(ctx context.Context, arg SendExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, sendExport, arg.SentBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
