// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueuedRunJobs = `-- name: CancelQueuedRunJobs :execrows
UPDATE jobs SET status = 'cancelled', finished_at = now(), updated_at = now()
WHERE run_id = $1 AND status = 'queued'
`

func (q *Queries) CancelQueuedRunJobs(ctx context.Context, runID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, cancelQueuedRunJobs, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', claimed_by = $1, claim_token = $2,
    lease_until = now() + make_interval(secs => $3::int),
    first_attempt_at = coalesce(first_attempt_at, now()), updated_at = now()
WHERE id = (
  SELECT id FROM jobs WHERE status = 'queued' AND run_after <= now()
  ORDER BY run_after, id FOR UPDATE SKIP LOCKED LIMIT 1
)
RETURNING id, type, run_id, product_id, listing_id, regeneration_request_id, attributes_revision, attempts, first_attempt_at
`

type ClaimJobParams struct {
	Worker       pgtype.Text `json:"worker"`
	ClaimToken   pgtype.UUID `json:"claim_token"`
	LeaseSeconds int32       `json:"lease_seconds"`
}

type ClaimJobRow struct {
	ID                    int64              `json:"id"`
	Type                  JobType            `json:"type"`
	RunID                 pgtype.Int8        `json:"run_id"`
	ProductID             int64              `json:"product_id"`
	ListingID             pgtype.Int8        `json:"listing_id"`
	RegenerationRequestID pgtype.Int8        `json:"regeneration_request_id"`
	AttributesRevision    pgtype.Int4        `json:"attributes_revision"`
	Attempts              int16              `json:"attempts"`
	FirstAttemptAt        pgtype.Timestamptz `json:"first_attempt_at"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.Worker, arg.ClaimToken, arg.LeaseSeconds)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RunID,
		&i.ProductID,
		&i.ListingID,
		&i.RegenerationRequestID,
		&i.AttributesRevision,
		&i.Attempts,
		&i.FirstAttemptAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO generation_runs (started_by, neutral_voice_confirmed) VALUES ($1, $2)
RETURNING id, created_at
`

type CreateRunParams struct {
	StartedBy             int64 `json:"started_by"`
	NeutralVoiceConfirmed bool  `json:"neutral_voice_confirmed"`
}

type CreateRunRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun, arg.StartedBy, arg.NeutralVoiceConfirmed)
	var i CreateRunRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (type, dedupe_key, run_id, product_id, listing_id, regeneration_request_id, attributes_revision)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (dedupe_key) WHERE status IN ('queued', 'running') DO NOTHING
RETURNING id
`

type EnqueueJobParams struct {
	Type                  JobType     `json:"type"`
	DedupeKey             string      `json:"dedupe_key"`
	RunID                 pgtype.Int8 `json:"run_id"`
	ProductID             int64       `json:"product_id"`
	ListingID             pgtype.Int8 `json:"listing_id"`
	RegenerationRequestID pgtype.Int8 `json:"regeneration_request_id"`
	AttributesRevision    pgtype.Int4 `json:"attributes_revision"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Type,
		arg.DedupeKey,
		arg.RunID,
		arg.ProductID,
		arg.ListingID,
		arg.RegenerationRequestID,
		arg.AttributesRevision,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishJob = `-- name: FinishJob :execrows
UPDATE jobs
SET status = $1, last_error = $2, finished_at = now(),
    claimed_by = NULL, claim_token = NULL, lease_until = NULL, updated_at = now()
WHERE id = $3 AND status = 'running' AND claim_token = $4
`

type FinishJobParams struct {
	Status     JobStatus   `json:"status"`
	LastError  pgtype.Text `json:"last_error"`
	ID         int64       `json:"id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJob,
		arg.Status,
		arg.LastError,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, created_at FROM generation_runs WHERE id = $1
`

type GetRunRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRun(ctx context.Context, id int64) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET status = 'queued', attempts = attempts + $1::smallint,
    run_after = now() + make_interval(secs => $2::int),
    last_error = $3,
    claimed_by = NULL, claim_token = NULL, lease_until = NULL, updated_at = now()
WHERE id = $4 AND status = 'running' AND claim_token = $5
`

type RetryJobParams struct {
	AddAttempt   int16       `json:"add_attempt"`
	DelaySeconds int32       `json:"delay_seconds"`
	LastError    pgtype.Text `json:"last_error"`
	ID           int64       `json:"id"`
	ClaimToken   pgtype.UUID `json:"claim_token"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.AddAttempt,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const runListingProgress = `-- name: RunListingProgress :one
SELECT
  count(*) FILTER (WHERE l.status = 'queued')::int AS queued,
  count(*) FILTER (WHERE l.status = 'generated')::int AS generated,
  count(*) FILTER (WHERE l.status = 'failed')::int AS failed,
  count(*) FILTER (WHERE l.status = 'stopped_budget')::int AS stopped
FROM listings l
WHERE l.product_id IN (SELECT DISTINCT j.product_id FROM jobs j WHERE j.run_id = $1)
`

type RunListingProgressRow struct {
	Queued    int32 `json:"queued"`
	Generated int32 `json:"generated"`
	Failed    int32 `json:"failed"`
	Stopped   int32 `json:"stopped"`
}

func (q *Queries) RunListingProgress(ctx context.Context, runID pgtype.Int8) (RunListingProgressRow, error) {
	row := q.db.QueryRow(ctx, runListingProgress, runID)
	var i RunListingProgressRow
	err := row.Scan(
		&i.Queued,
		&i.Generated,
		&i.Failed,
		&i.Stopped,
	)
	return i, err
}

const runProductIDs = `-- name: RunProductIDs :many
SELECT DISTINCT product_id FROM jobs WHERE run_id = $1 ORDER BY product_id
`

func (q *Queries) RunProductIDs(ctx context.Context, runID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, runProductIDs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var product_id int64
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runProgress = `-- name: RunProgress :one
SELECT
  count(*) FILTER (WHERE pa.detection_status = 'pending')::int AS detection_pending,
  count(*) FILTER (WHERE pa.detection_status = 'done')::int AS detection_done,
  count(*) FILTER (WHERE pa.detection_status = 'failed')::int AS detection_failed,
  count(*) FILTER (WHERE pa.detection_status = 'stopped_budget')::int AS detection_stopped
FROM product_attributes pa
WHERE pa.product_id IN (SELECT DISTINCT j.product_id FROM jobs j WHERE j.run_id = $1)
`

type RunProgressRow struct {
	DetectionPending int32 `json:"detection_pending"`
	DetectionDone    int32 `json:"detection_done"`
	DetectionFailed  int32 `json:"detection_failed"`
	DetectionStopped int32 `json:"detection_stopped"`
}

func (q *Queries) RunProgress(ctx context.Context, runID pgtype.Int8) (RunProgressRow, error) {
	row := q.db.QueryRow(ctx, runProgress, runID)
	var i RunProgressRow
	err := row.Scan(
		&i.DetectionPending,
		&i.DetectionDone,
		&i.DetectionFailed,
		&i.DetectionStopped,
	)
	return i, err
}

const sweepStaleJobs = `-- name: SweepStaleJobs :execrows
UPDATE jobs
SET status = CASE WHEN attempts + 1 >= 3 THEN 'failed'::job_status ELSE 'queued'::job_status END,
    attempts = attempts + 1,
    finished_at = CASE WHEN attempts + 1 >= 3 THEN now() END,
    last_error = 'worker stopped before finishing',
    claimed_by = NULL, claim_token = NULL, lease_until = NULL, updated_at = now()
WHERE status = 'running' AND lease_until < now()
`

func (q *Queries) SweepStaleJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
