// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveIfCurrent = `-- name: ApproveIfCurrent :one
INSERT INTO approvals (listing_id, listing_version, approved_by)
SELECT l.id, l.version, $1 FROM listings l
WHERE l.id = $2 AND l.version = $3
  AND l.status = 'generated' AND l.rule_status = 'passing'
ON CONFLICT (listing_id, listing_version) DO UPDATE SET listing_id = approvals.listing_id
RETURNING created_at
`

type ApproveIfCurrentParams struct {
	ApprovedBy     int64 `json:"approved_by"`
	ListingID      int64 `json:"listing_id"`
	ListingVersion int32 `json:"listing_version"`
}

func (q *Queries) ApproveIfCurrent(ctx context.Context, arg ApproveIfCurrentParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, approveIfCurrent, arg.ApprovedBy, arg.ListingID, arg.ListingVersion)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const bumpListing = `-- name: BumpListing :exec
UPDATE listings SET version = version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) BumpListing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpListing, id)
	return err
}

const bumpProductListings = `-- name: BumpProductListings :many
UPDATE listings SET version = version + 1, rule_status = 'failing', updated_at = now()
WHERE product_id = $1 AND status = 'generated'
RETURNING id
`

func (q *Queries) BumpProductListings(ctx context.Context, productID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, bumpProductListings, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctAttributes = `-- name: CorrectAttributes :one
UPDATE product_attributes
SET colour = coalesce($1, colour),
    pattern = coalesce($2, pattern),
    sleeve = coalesce($3, sleeve),
    neckline = coalesce($4, neckline),
    fit = coalesce($5, fit),
    corrected_by = $6,
    -- A reviewer's correction is certain; it leaves the low-confidence list.
    detection_confidence = NULL,
    revision = revision + 1,
    updated_at = now()
WHERE product_id = $7 AND revision = $8
  AND detection_status = 'done'
RETURNING product_id, detection_status, revision, colour, pattern, sleeve, neckline, fit, detection_error
`

type CorrectAttributesParams struct {
	Colour           pgtype.Text `json:"colour"`
	Pattern          pgtype.Text `json:"pattern"`
	Sleeve           pgtype.Text `json:"sleeve"`
	Neckline         pgtype.Text `json:"neckline"`
	Fit              pgtype.Text `json:"fit"`
	CorrectedBy      pgtype.Int8 `json:"corrected_by"`
	ProductID        int64       `json:"product_id"`
	ExpectedRevision int32       `json:"expected_revision"`
}

type CorrectAttributesRow struct {
	ProductID       int64           `json:"product_id"`
	DetectionStatus DetectionStatus `json:"detection_status"`
	Revision        int32           `json:"revision"`
	Colour          pgtype.Text     `json:"colour"`
	Pattern         pgtype.Text     `json:"pattern"`
	Sleeve          pgtype.Text     `json:"sleeve"`
	Neckline        pgtype.Text     `json:"neckline"`
	Fit             pgtype.Text     `json:"fit"`
	DetectionError  pgtype.Text     `json:"detection_error"`
}

func (q *Queries) CorrectAttributes(ctx context.Context, arg CorrectAttributesParams) (CorrectAttributesRow, error) {
	row := q.db.QueryRow(ctx, correctAttributes,
		arg.Colour,
		arg.Pattern,
		arg.Sleeve,
		arg.Neckline,
		arg.Fit,
		arg.CorrectedBy,
		arg.ProductID,
		arg.ExpectedRevision,
	)
	var i CorrectAttributesRow
	err := row.Scan(
		&i.ProductID,
		&i.DetectionStatus,
		&i.Revision,
		&i.Colour,
		&i.Pattern,
		&i.Sleeve,
		&i.Neckline,
		&i.Fit,
		&i.DetectionError,
	)
	return i, err
}

const createRegeneration = `-- name: CreateRegeneration :one
INSERT INTO regeneration_requests (listing_id, field, instruction, base_value, requested_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, listing_id, field, instruction, status, created_at
`

type CreateRegenerationParams struct {
	ListingID   int64  `json:"listing_id"`
	Field       string `json:"field"`
	Instruction string `json:"instruction"`
	BaseValue   string `json:"base_value"`
	RequestedBy int64  `json:"requested_by"`
}

type CreateRegenerationRow struct {
	ID          int64              `json:"id"`
	ListingID   int64              `json:"listing_id"`
	Field       string             `json:"field"`
	Instruction string             `json:"instruction"`
	Status      RegenerationStatus `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRegeneration(ctx context.Context, arg CreateRegenerationParams) (CreateRegenerationRow, error) {
	row := q.db.QueryRow(ctx, createRegeneration,
		arg.ListingID,
		arg.Field,
		arg.Instruction,
		arg.BaseValue,
		arg.RequestedBy,
	)
	var i CreateRegenerationRow
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.Field,
		&i.Instruction,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRuleResults = `-- name: DeleteRuleResults :exec
DELETE FROM rule_results WHERE listing_id = $1
`

func (q *Queries) DeleteRuleResults(ctx context.Context, listingID int64) error {
	_, err := q.db.Exec(ctx, deleteRuleResults, listingID)
	return err
}

const endQueuedListingsForProduct = `-- name: EndQueuedListingsForProduct :exec
UPDATE listings SET status = $2, failure_reason = $3, updated_at = now()
WHERE product_id = $1 AND status = 'queued'
`

type EndQueuedListingsForProductParams struct {
	ProductID     int64         `json:"product_id"`
	Status        ListingStatus `json:"status"`
	FailureReason pgtype.Text   `json:"failure_reason"`
}

func (q *Queries) EndQueuedListingsForProduct(ctx context.Context, arg EndQueuedListingsForProductParams) error {
	_, err := q.db.Exec(ctx, endQueuedListingsForProduct, arg.ProductID, arg.Status, arg.FailureReason)
	return err
}

const ensureAttributes = `-- name: EnsureAttributes :exec
INSERT INTO product_attributes (product_id) VALUES ($1) ON CONFLICT (product_id) DO NOTHING
`

func (q *Queries) EnsureAttributes(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, ensureAttributes, productID)
	return err
}

const forceDetectionPending = `-- name: ForceDetectionPending :exec
UPDATE product_attributes
SET detection_status = 'pending', detection_error = NULL, updated_at = now()
WHERE product_id = $1
`

func (q *Queries) ForceDetectionPending(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, forceDetectionPending, productID)
	return err
}

const getAttributes = `-- name: GetAttributes :one
SELECT product_id, detection_status, revision, colour, pattern, sleeve, neckline, fit, detection_error
FROM product_attributes WHERE product_id = $1
`

type GetAttributesRow struct {
	ProductID       int64           `json:"product_id"`
	DetectionStatus DetectionStatus `json:"detection_status"`
	Revision        int32           `json:"revision"`
	Colour          pgtype.Text     `json:"colour"`
	Pattern         pgtype.Text     `json:"pattern"`
	Sleeve          pgtype.Text     `json:"sleeve"`
	Neckline        pgtype.Text     `json:"neckline"`
	Fit             pgtype.Text     `json:"fit"`
	DetectionError  pgtype.Text     `json:"detection_error"`
}

func (q *Queries) GetAttributes(ctx context.Context, productID int64) (GetAttributesRow, error) {
	row := q.db.QueryRow(ctx, getAttributes, productID)
	var i GetAttributesRow
	err := row.Scan(
		&i.ProductID,
		&i.DetectionStatus,
		&i.Revision,
		&i.Colour,
		&i.Pattern,
		&i.Sleeve,
		&i.Neckline,
		&i.Fit,
		&i.DetectionError,
	)
	return i, err
}

const getAttributesForUpdate = `-- name: GetAttributesForUpdate :one
SELECT product_id, detection_status, revision, colour, pattern, sleeve, neckline, fit, detection_error
FROM product_attributes WHERE product_id = $1 FOR UPDATE
`

type GetAttributesForUpdateRow struct {
	ProductID       int64           `json:"product_id"`
	DetectionStatus DetectionStatus `json:"detection_status"`
	Revision        int32           `json:"revision"`
	Colour          pgtype.Text     `json:"colour"`
	Pattern         pgtype.Text     `json:"pattern"`
	Sleeve          pgtype.Text     `json:"sleeve"`
	Neckline        pgtype.Text     `json:"neckline"`
	Fit             pgtype.Text     `json:"fit"`
	DetectionError  pgtype.Text     `json:"detection_error"`
}

func (q *Queries) GetAttributesForUpdate(ctx context.Context, productID int64) (GetAttributesForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAttributesForUpdate, productID)
	var i GetAttributesForUpdateRow
	err := row.Scan(
		&i.ProductID,
		&i.DetectionStatus,
		&i.Revision,
		&i.Colour,
		&i.Pattern,
		&i.Sleeve,
		&i.Neckline,
		&i.Fit,
		&i.DetectionError,
	)
	return i, err
}

const getListing = `-- name: GetListing :one
SELECT l.id, l.product_id, l.channel, l.status, l.failure_reason, l.version,
       l.title, l.bullet_1, l.bullet_2, l.bullet_3, l.bullet_4, l.bullet_5, l.description,
       l.rule_status, l.rule_config_hash, l.first_pass_passed, p.sku
FROM listings l JOIN products p ON p.id = l.product_id
WHERE l.id = $1
`

type GetListingRow struct {
	ID              int64         `json:"id"`
	ProductID       int64         `json:"product_id"`
	Channel         string        `json:"channel"`
	Status          ListingStatus `json:"status"`
	FailureReason   pgtype.Text   `json:"failure_reason"`
	Version         int32         `json:"version"`
	Title           pgtype.Text   `json:"title"`
	Bullet1         pgtype.Text   `json:"bullet_1"`
	Bullet2         pgtype.Text   `json:"bullet_2"`
	Bullet3         pgtype.Text   `json:"bullet_3"`
	Bullet4         pgtype.Text   `json:"bullet_4"`
	Bullet5         pgtype.Text   `json:"bullet_5"`
	Description     pgtype.Text   `json:"description"`
	RuleStatus      RuleStatus    `json:"rule_status"`
	RuleConfigHash  pgtype.Text   `json:"rule_config_hash"`
	FirstPassPassed pgtype.Bool   `json:"first_pass_passed"`
	Sku             string        `json:"sku"`
}

func (q *Queries) GetListing(ctx context.Context, id int64) (GetListingRow, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i GetListingRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Channel,
		&i.Status,
		&i.FailureReason,
		&i.Version,
		&i.Title,
		&i.Bullet1,
		&i.Bullet2,
		&i.Bullet3,
		&i.Bullet4,
		&i.Bullet5,
		&i.Description,
		&i.RuleStatus,
		&i.RuleConfigHash,
		&i.FirstPassPassed,
		&i.Sku,
	)
	return i, err
}

const getListingForUpdate = `-- name: GetListingForUpdate :one
SELECT id, product_id, channel, status, version, title, bullet_1, bullet_2, bullet_3, bullet_4, bullet_5, description, rule_status
FROM listings WHERE id = $1 FOR UPDATE
`

type GetListingForUpdateRow struct {
	ID          int64         `json:"id"`
	ProductID   int64         `json:"product_id"`
	Channel     string        `json:"channel"`
	Status      ListingStatus `json:"status"`
	Version     int32         `json:"version"`
	Title       pgtype.Text   `json:"title"`
	Bullet1     pgtype.Text   `json:"bullet_1"`
	Bullet2     pgtype.Text   `json:"bullet_2"`
	Bullet3     pgtype.Text   `json:"bullet_3"`
	Bullet4     pgtype.Text   `json:"bullet_4"`
	Bullet5     pgtype.Text   `json:"bullet_5"`
	Description pgtype.Text   `json:"description"`
	RuleStatus  RuleStatus    `json:"rule_status"`
}

func (q *Queries) GetListingForUpdate(ctx context.Context, id int64) (GetListingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getListingForUpdate, id)
	var i GetListingForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Channel,
		&i.Status,
		&i.Version,
		&i.Title,
		&i.Bullet1,
		&i.Bullet2,
		&i.Bullet3,
		&i.Bullet4,
		&i.Bullet5,
		&i.Description,
		&i.RuleStatus,
	)
	return i, err
}

const getRegeneration = `-- name: GetRegeneration :one
SELECT id, listing_id, field, instruction, base_value, status FROM regeneration_requests WHERE id = $1
`

type GetRegenerationRow struct {
	ID          int64              `json:"id"`
	ListingID   int64              `json:"listing_id"`
	Field       string             `json:"field"`
	Instruction string             `json:"instruction"`
	BaseValue   string             `json:"base_value"`
	Status      RegenerationStatus `json:"status"`
}

func (q *Queries) GetRegeneration(ctx context.Context, id int64) (GetRegenerationRow, error) {
	row := q.db.QueryRow(ctx, getRegeneration, id)
	var i GetRegenerationRow
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.Field,
		&i.Instruction,
		&i.BaseValue,
		&i.Status,
	)
	return i, err
}

const insertConfigRecheck = `-- name: InsertConfigRecheck :exec
INSERT INTO config_rechecks (channel, config_hash, listings_rechecked, approvals_cleared)
VALUES ($1, $2, $3, $4)
`

type InsertConfigRecheckParams struct {
	Channel           string `json:"channel"`
	ConfigHash        string `json:"config_hash"`
	ListingsRechecked int32  `json:"listings_rechecked"`
	ApprovalsCleared  int32  `json:"approvals_cleared"`
}

func (q *Queries) InsertConfigRecheck(ctx context.Context, arg InsertConfigRecheckParams) error {
	_, err := q.db.Exec(ctx, insertConfigRecheck,
		arg.Channel,
		arg.ConfigHash,
		arg.ListingsRechecked,
		arg.ApprovalsCleared,
	)
	return err
}

const insertRuleResult = `-- name: InsertRuleResult :exec
INSERT INTO rule_results (listing_id, listing_version, rule, field, message, config_hash)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRuleResultParams struct {
	ListingID      int64  `json:"listing_id"`
	ListingVersion int32  `json:"listing_version"`
	Rule           string `json:"rule"`
	Field          string `json:"field"`
	Message        string `json:"message"`
	ConfigHash     string `json:"config_hash"`
}

func (q *Queries) InsertRuleResult(ctx context.Context, arg InsertRuleResultParams) error {
	_, err := q.db.Exec(ctx, insertRuleResult,
		arg.ListingID,
		arg.ListingVersion,
		arg.Rule,
		arg.Field,
		arg.Message,
		arg.ConfigHash,
	)
	return err
}

const isApprovedNow = `-- name: IsApprovedNow :one
SELECT EXISTS (
  SELECT 1 FROM approvals a JOIN listings l ON l.id = a.listing_id
  WHERE a.listing_id = $1 AND a.listing_version = l.version
)::boolean
`

func (q *Queries) IsApprovedNow(ctx context.Context, listingID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isApprovedNow, listingID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const latestRechecks = `-- name: LatestRechecks :many
SELECT DISTINCT ON (channel) channel, config_hash, listings_rechecked, approvals_cleared, created_at
FROM config_rechecks ORDER BY channel, created_at DESC
`

type LatestRechecksRow struct {
	Channel           string             `json:"channel"`
	ConfigHash        string             `json:"config_hash"`
	ListingsRechecked int32              `json:"listings_rechecked"`
	ApprovalsCleared  int32              `json:"approvals_cleared"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestRechecks(ctx context.Context) ([]LatestRechecksRow, error) {
	rows, err := q.db.Query(ctx, latestRechecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRechecksRow
	for rows.Next() {
		var i LatestRechecksRow
		if err := rows.Scan(
			&i.Channel,
			&i.ConfigHash,
			&i.ListingsRechecked,
			&i.ApprovalsCleared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRegenerations = `-- name: LatestRegenerations :many
SELECT DISTINCT ON (listing_id) listing_id, field, status FROM regeneration_requests
WHERE listing_id = ANY($1::bigint[])
ORDER BY listing_id, id DESC
`

type LatestRegenerationsRow struct {
	ListingID int64              `json:"listing_id"`
	Field     string             `json:"field"`
	Status    RegenerationStatus `json:"status"`
}

func (q *Queries) LatestRegenerations(ctx context.Context, listingIds []int64) ([]LatestRegenerationsRow, error) {
	rows, err := q.db.Query(ctx, latestRegenerations, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRegenerationsRow
	for rows.Next() {
		var i LatestRegenerationsRow
		if err := rows.Scan(&i.ListingID, &i.Field, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrid = `-- name: ListGrid :many
SELECT l.id, l.product_id, p.sku, l.channel, l.status, l.failure_reason, l.version,
       l.title, l.bullet_1, l.bullet_2, l.bullet_3, l.bullet_4, l.bullet_5, l.description,
       l.rule_status,
       a.approved_at AS approved_at, u.email AS approved_by,
       pa.colour, pa.pattern, pa.sleeve, pa.neckline, pa.fit, coalesce(pa.revision, 0)::int AS attributes_revision
FROM listings l
JOIN products p ON p.id = l.product_id
LEFT JOIN product_attributes pa ON pa.product_id = l.product_id
LEFT JOIN LATERAL (
  SELECT ap.created_at AS approved_at, ap.approved_by FROM approvals ap
  WHERE ap.listing_id = l.id AND ap.listing_version = l.version LIMIT 1
) a ON true
LEFT JOIN users u ON u.id = a.approved_by
WHERE ($1::text IS NULL OR l.channel = $1)
  AND ($2::rule_status IS NULL OR l.rule_status = $2)
  AND ($3::boolean IS NULL OR (a.approved_at IS NOT NULL) = $3)
  AND ($4::bigint IS NULL OR l.id = $4)
  AND ($5::bigint IS NULL OR p.upload_id = $5)
  AND (lower(p.sku), l.channel) > (lower($6::text), $7::text)
ORDER BY lower(p.sku), l.channel
LIMIT $8
`

type ListGridParams struct {
	Channel      pgtype.Text    `json:"channel"`
	RuleStatus   NullRuleStatus `json:"rule_status"`
	Approved     pgtype.Bool    `json:"approved"`
	ListingID    pgtype.Int8    `json:"listing_id"`
	UploadID     pgtype.Int8    `json:"upload_id"`
	AfterSku     string         `json:"after_sku"`
	AfterChannel string         `json:"after_channel"`
	PageSize     int32          `json:"page_size"`
}

type ListGridRow struct {
	ID                 int64              `json:"id"`
	ProductID          int64              `json:"product_id"`
	Sku                string             `json:"sku"`
	Channel            string             `json:"channel"`
	Status             ListingStatus      `json:"status"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	Version            int32              `json:"version"`
	Title              pgtype.Text        `json:"title"`
	Bullet1            pgtype.Text        `json:"bullet_1"`
	Bullet2            pgtype.Text        `json:"bullet_2"`
	Bullet3            pgtype.Text        `json:"bullet_3"`
	Bullet4            pgtype.Text        `json:"bullet_4"`
	Bullet5            pgtype.Text        `json:"bullet_5"`
	Description        pgtype.Text        `json:"description"`
	RuleStatus         RuleStatus         `json:"rule_status"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy         pgtype.Text        `json:"approved_by"`
	Colour             pgtype.Text        `json:"colour"`
	Pattern            pgtype.Text        `json:"pattern"`
	Sleeve             pgtype.Text        `json:"sleeve"`
	Neckline           pgtype.Text        `json:"neckline"`
	Fit                pgtype.Text        `json:"fit"`
	AttributesRevision int32              `json:"attributes_revision"`
}

func (q *Queries) ListGrid(ctx context.Context, arg ListGridParams) ([]ListGridRow, error) {
	rows, err := q.db.Query(ctx, listGrid,
		arg.Channel,
		arg.RuleStatus,
		arg.Approved,
		arg.ListingID,
		arg.UploadID,
		arg.AfterSku,
		arg.AfterChannel,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGridRow
	for rows.Next() {
		var i ListGridRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Channel,
			&i.Status,
			&i.FailureReason,
			&i.Version,
			&i.Title,
			&i.Bullet1,
			&i.Bullet2,
			&i.Bullet3,
			&i.Bullet4,
			&i.Bullet5,
			&i.Description,
			&i.RuleStatus,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.Colour,
			&i.Pattern,
			&i.Sleeve,
			&i.Neckline,
			&i.Fit,
			&i.AttributesRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegenerations = `-- name: ListRegenerations :many
SELECT id, listing_id, field, instruction, status, created_at FROM regeneration_requests
WHERE listing_id = $1 AND id < $2
ORDER BY id DESC LIMIT $3
`

type ListRegenerationsParams struct {
	ListingID int64 `json:"listing_id"`
	BeforeID  int64 `json:"before_id"`
	PageSize  int32 `json:"page_size"`
}

type ListRegenerationsRow struct {
	ID          int64              `json:"id"`
	ListingID   int64              `json:"listing_id"`
	Field       string             `json:"field"`
	Instruction string             `json:"instruction"`
	Status      RegenerationStatus `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRegenerations(ctx context.Context, arg ListRegenerationsParams) ([]ListRegenerationsRow, error) {
	rows, err := q.db.Query(ctx, listRegenerations, arg.ListingID, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegenerationsRow
	for rows.Next() {
		var i ListRegenerationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Field,
			&i.Instruction,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleResults = `-- name: ListRuleResults :many
SELECT listing_id, rule, field, message FROM rule_results
WHERE listing_id = ANY($1::bigint[])
ORDER BY listing_id, id
`

type ListRuleResultsRow struct {
	ListingID int64  `json:"listing_id"`
	Rule      string `json:"rule"`
	Field     string `json:"field"`
	Message   string `json:"message"`
}

func (q *Queries) ListRuleResults(ctx context.Context, listingIds []int64) ([]ListRuleResultsRow, error) {
	rows, err := q.db.Query(ctx, listRuleResults, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleResultsRow
	for rows.Next() {
		var i ListRuleResultsRow
		if err := rows.Scan(
			&i.ListingID,
			&i.Rule,
			&i.Field,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsForRecheck = `-- name: ListingsForRecheck :many
SELECT l.id FROM listings l
WHERE l.channel = $1 AND l.status = 'generated'
  AND (l.rule_config_hash IS NULL OR l.rule_config_hash <> $2::text)
ORDER BY l.id
`

type ListingsForRecheckParams struct {
	Channel    string `json:"channel"`
	ConfigHash string `json:"config_hash"`
}

func (q *Queries) ListingsForRecheck(ctx context.Context, arg ListingsForRecheckParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listingsForRecheck, arg.Channel, arg.ConfigHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueListing = `-- name: QueueListing :one
INSERT INTO listings (product_id, channel) VALUES ($1, $2)
ON CONFLICT (product_id, channel) DO UPDATE
SET status = 'queued', failure_reason = NULL, updated_at = now()
WHERE listings.status IN ('failed', 'stopped_budget')
RETURNING id
`

type QueueListingParams struct {
	ProductID int64  `json:"product_id"`
	Channel   string `json:"channel"`
}

func (q *Queries) QueueListing(ctx context.Context, arg QueueListingParams) (int64, error) {
	row := q.db.QueryRow(ctx, queueListing, arg.ProductID, arg.Channel)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const queuedListingsForProduct = `-- name: QueuedListingsForProduct :many
SELECT id, channel FROM listings WHERE product_id = $1 AND status = 'queued' ORDER BY channel
`

type QueuedListingsForProductRow struct {
	ID      int64  `json:"id"`
	Channel string `json:"channel"`
}

func (q *Queries) QueuedListingsForProduct(ctx context.Context, productID int64) ([]QueuedListingsForProductRow, error) {
	rows, err := q.db.Query(ctx, queuedListingsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueuedListingsForProductRow
	for rows.Next() {
		var i QueuedListingsForProductRow
		if err := rows.Scan(&i.ID, &i.Channel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueProductListings = `-- name: RequeueProductListings :exec
UPDATE listings SET status = 'queued', failure_reason = NULL, version = version + 1, updated_at = now()
WHERE product_id = $1
`

// A re-run rewrites every channel's listing; the version rises so no older
// approval can match the new text.
func (q *Queries) RequeueProductListings(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, requeueProductListings, productID)
	return err
}

const resetDetectionPending = `-- name: ResetDetectionPending :exec
UPDATE product_attributes
SET detection_status = 'pending', detection_error = NULL, updated_at = now()
WHERE product_id = $1 AND detection_status IN ('failed', 'stopped_budget')
`

func (q *Queries) ResetDetectionPending(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, resetDetectionPending, productID)
	return err
}

const setDetectionDone = `-- name: SetDetectionDone :one
UPDATE product_attributes
SET detection_status = 'done', colour = $2, pattern = $3, sleeve = $4, neckline = $5, fit = $6,
    detection_confidence = $7::real,
    detection_error = NULL, revision = revision + 1, updated_at = now()
WHERE product_id = $1
RETURNING revision
`

type SetDetectionDoneParams struct {
	ProductID  int64         `json:"product_id"`
	Colour     pgtype.Text   `json:"colour"`
	Pattern    pgtype.Text   `json:"pattern"`
	Sleeve     pgtype.Text   `json:"sleeve"`
	Neckline   pgtype.Text   `json:"neckline"`
	Fit        pgtype.Text   `json:"fit"`
	Confidence pgtype.Float4 `json:"confidence"`
}

func (q *Queries) SetDetectionDone(ctx context.Context, arg SetDetectionDoneParams) (int32, error) {
	row := q.db.QueryRow(ctx, setDetectionDone,
		arg.ProductID,
		arg.Colour,
		arg.Pattern,
		arg.Sleeve,
		arg.Neckline,
		arg.Fit,
		arg.Confidence,
	)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const setDetectionEnded = `-- name: SetDetectionEnded :exec
UPDATE product_attributes
SET detection_status = $2, detection_error = $3, updated_at = now()
WHERE product_id = $1
`

type SetDetectionEndedParams struct {
	ProductID       int64           `json:"product_id"`
	DetectionStatus DetectionStatus `json:"detection_status"`
	DetectionError  pgtype.Text     `json:"detection_error"`
}

func (q *Queries) SetDetectionEnded(ctx context.Context, arg SetDetectionEndedParams) error {
	_, err := q.db.Exec(ctx, setDetectionEnded, arg.ProductID, arg.DetectionStatus, arg.DetectionError)
	return err
}

const setFieldIfUnchanged = `-- name: SetFieldIfUnchanged :one
UPDATE listings
SET title = CASE WHEN $1::text = 'title' THEN $2::text ELSE title END,
    bullet_1 = CASE WHEN $1::text = 'bullet_1' THEN $2::text ELSE bullet_1 END,
    bullet_2 = CASE WHEN $1::text = 'bullet_2' THEN $2::text ELSE bullet_2 END,
    bullet_3 = CASE WHEN $1::text = 'bullet_3' THEN $2::text ELSE bullet_3 END,
    bullet_4 = CASE WHEN $1::text = 'bullet_4' THEN $2::text ELSE bullet_4 END,
    bullet_5 = CASE WHEN $1::text = 'bullet_5' THEN $2::text ELSE bullet_5 END,
    description = CASE WHEN $1::text = 'description' THEN $2::text ELSE description END,
    version = version + 1, rule_status = 'failing', updated_at = now()
WHERE id = $3 AND status = 'generated'
  AND CASE $1::text
        WHEN 'title' THEN title WHEN 'bullet_1' THEN bullet_1 WHEN 'bullet_2' THEN bullet_2
        WHEN 'bullet_3' THEN bullet_3 WHEN 'bullet_4' THEN bullet_4 WHEN 'bullet_5' THEN bullet_5
        WHEN 'description' THEN description END = $4::text
RETURNING version
`

type SetFieldIfUnchangedParams struct {
	Field     string `json:"field"`
	Value     string `json:"value"`
	ID        int64  `json:"id"`
	BaseValue string `json:"base_value"`
}

func (q *Queries) SetFieldIfUnchanged(ctx context.Context, arg SetFieldIfUnchangedParams) (int32, error) {
	row := q.db.QueryRow(ctx, setFieldIfUnchanged,
		arg.Field,
		arg.Value,
		arg.ID,
		arg.BaseValue,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const setListingEnded = `-- name: SetListingEnded :exec
UPDATE listings SET status = $2, failure_reason = $3, updated_at = now()
WHERE id = $1
`

type SetListingEndedParams struct {
	ID            int64         `json:"id"`
	Status        ListingStatus `json:"status"`
	FailureReason pgtype.Text   `json:"failure_reason"`
}

func (q *Queries) SetListingEnded(ctx context.Context, arg SetListingEndedParams) error {
	_, err := q.db.Exec(ctx, setListingEnded, arg.ID, arg.Status, arg.FailureReason)
	return err
}

const setRegenerationStatus = `-- name: SetRegenerationStatus :exec
UPDATE regeneration_requests SET status = $2, updated_at = now() WHERE id = $1
`

type SetRegenerationStatusParams struct {
	ID     int64              `json:"id"`
	Status RegenerationStatus `json:"status"`
}

func (q *Queries) SetRegenerationStatus(ctx context.Context, arg SetRegenerationStatusParams) error {
	_, err := q.db.Exec(ctx, setRegenerationStatus, arg.ID, arg.Status)
	return err
}

const setRuleStatus = `-- name: SetRuleStatus :exec
UPDATE listings
SET rule_status = $2, rule_config_hash = $3,
    first_pass_passed = coalesce(first_pass_passed, $4::boolean),
    first_pass_failed_rules = coalesce(first_pass_failed_rules, $5::text[]),
    updated_at = now()
WHERE id = $1
`

type SetRuleStatusParams struct {
	ID                   int64       `json:"id"`
	RuleStatus           RuleStatus  `json:"rule_status"`
	RuleConfigHash       pgtype.Text `json:"rule_config_hash"`
	FirstPassPassed      bool        `json:"first_pass_passed"`
	FirstPassFailedRules []string    `json:"first_pass_failed_rules"`
}

func (q *Queries) SetRuleStatus(ctx context.Context, arg SetRuleStatusParams) error {
	_, err := q.db.Exec(ctx, setRuleStatus,
		arg.ID,
		arg.RuleStatus,
		arg.RuleConfigHash,
		arg.FirstPassPassed,
		arg.FirstPassFailedRules,
	)
	return err
}

const updateListingText = `-- name: UpdateListingText :one
UPDATE listings
SET title = coalesce($1, title),
    bullet_1 = coalesce($2, bullet_1),
    bullet_2 = coalesce($3, bullet_2),
    bullet_3 = coalesce($4, bullet_3),
    bullet_4 = coalesce($5, bullet_4),
    bullet_5 = coalesce($6, bullet_5),
    description = coalesce($7, description),
    version = version + 1, rule_status = 'failing', updated_at = now()
WHERE id = $8 AND version = $9 AND status = 'generated'
RETURNING version
`

type UpdateListingTextParams struct {
	Title           pgtype.Text `json:"title"`
	Bullet1         pgtype.Text `json:"bullet_1"`
	Bullet2         pgtype.Text `json:"bullet_2"`
	Bullet3         pgtype.Text `json:"bullet_3"`
	Bullet4         pgtype.Text `json:"bullet_4"`
	Bullet5         pgtype.Text `json:"bullet_5"`
	Description     pgtype.Text `json:"description"`
	ID              int64       `json:"id"`
	ExpectedVersion int32       `json:"expected_version"`
}

func (q *Queries) UpdateListingText(ctx context.Context, arg UpdateListingTextParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateListingText,
		arg.Title,
		arg.Bullet1,
		arg.Bullet2,
		arg.Bullet3,
		arg.Bullet4,
		arg.Bullet5,
		arg.Description,
		arg.ID,
		arg.ExpectedVersion,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const writeGenerated = `-- name: WriteGenerated :one

UPDATE listings
SET status = 'generated', failure_reason = NULL, version = version + 1,
    title = $2, bullet_1 = $3, bullet_2 = $4, bullet_3 = $5, bullet_4 = $6, bullet_5 = $7,
    description = $8, rule_status = 'failing', updated_at = now()
WHERE id = $1
RETURNING version
`

type WriteGeneratedParams struct {
	ID          int64       `json:"id"`
	Title       pgtype.Text `json:"title"`
	Bullet1     pgtype.Text `json:"bullet_1"`
	Bullet2     pgtype.Text `json:"bullet_2"`
	Bullet3     pgtype.Text `json:"bullet_3"`
	Bullet4     pgtype.Text `json:"bullet_4"`
	Bullet5     pgtype.Text `json:"bullet_5"`
	Description pgtype.Text `json:"description"`
}

// A text or attribute change sets rule_status to failing as a placeholder:
// a generated listing is never unchecked (chk_listings_generated_checked), and
// Revalidate sets the real status in the same transaction. A listing of a
// switched-off channel stays failing, so it cannot be approved (D8).
func (q *Queries) WriteGenerated(ctx context.Context, arg WriteGeneratedParams) (int32, error) {
	row := q.db.QueryRow(ctx, writeGenerated,
		arg.ID,
		arg.Title,
		arg.Bullet1,
		arg.Bullet2,
		arg.Bullet3,
		arg.Bullet4,
		arg.Bullet5,
		arg.Description,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
