// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package store

import (
	"context"
)

const countProbes = `-- name: CountProbes :one
SELECT count(*) FROM schema_probe
`

func (q *Queries) CountProbes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProbes)
	var count int64
	err := row.Scan(&count)
	return count, err
}
