// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, csrf_token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash     string             `json:"token_hash"`
	UserID        int64              `json:"user_id"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, role, password_hash)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	Role         UserRole `json:"role"`
	PasswordHash string   `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Role, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.user_id, s.csrf_token_hash, s.expires_at, u.email, u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	UserID        int64              `json:"user_id"`
	CsrfTokenHash string             `json:"csrf_token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Email         string             `json:"email"`
	Role          UserRole           `json:"role"`
}

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.CsrfTokenHash,
		&i.ExpiresAt,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, password_hash FROM users WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID           int64    `json:"id"`
	Email        string   `json:"email"`
	Role         UserRole `json:"role"`
	PasswordHash string   `json:"password_hash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users SET password_hash = $2, updated_at = now() WHERE lower(email) = lower($1)
`

type SetUserPasswordParams struct {
	Lower        string `json:"lower"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPassword, arg.Lower, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
