// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiCallPurpose string

const (
	AiCallPurposeDetect     AiCallPurpose = "detect"
	AiCallPurposeGenerate   AiCallPurpose = "generate"
	AiCallPurposeRegenerate AiCallPurpose = "regenerate"
	AiCallPurposeEvalDetect AiCallPurpose = "eval_detect"
)

func (e *AiCallPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiCallPurpose(s)
	case string:
		*e = AiCallPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for AiCallPurpose: %T", src)
	}
	return nil
}

type NullAiCallPurpose struct {
	AiCallPurpose AiCallPurpose `json:"ai_call_purpose"`
	Valid         bool          `json:"valid"` // Valid is true if AiCallPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiCallPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.AiCallPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiCallPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiCallPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiCallPurpose), nil
}

type AiCallStatus string

const (
	AiCallStatusReserved        AiCallStatus = "reserved"
	AiCallStatusSucceeded       AiCallStatus = "succeeded"
	AiCallStatusFailed          AiCallStatus = "failed"
	AiCallStatusPossiblyCharged AiCallStatus = "possibly_charged"
)

func (e *AiCallStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiCallStatus(s)
	case string:
		*e = AiCallStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AiCallStatus: %T", src)
	}
	return nil
}

type NullAiCallStatus struct {
	AiCallStatus AiCallStatus `json:"ai_call_status"`
	Valid        bool         `json:"valid"` // Valid is true if AiCallStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiCallStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AiCallStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiCallStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiCallStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiCallStatus), nil
}

type DetectionStatus string

const (
	DetectionStatusPending       DetectionStatus = "pending"
	DetectionStatusDone          DetectionStatus = "done"
	DetectionStatusFailed        DetectionStatus = "failed"
	DetectionStatusStoppedBudget DetectionStatus = "stopped_budget"
)

func (e *DetectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DetectionStatus(s)
	case string:
		*e = DetectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DetectionStatus: %T", src)
	}
	return nil
}

type NullDetectionStatus struct {
	DetectionStatus DetectionStatus `json:"detection_status"`
	Valid           bool            `json:"valid"` // Valid is true if DetectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDetectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DetectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DetectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDetectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DetectionStatus), nil
}

type JobStatus string

const (
	JobStatusQueued        JobStatus = "queued"
	JobStatusRunning       JobStatus = "running"
	JobStatusDone          JobStatus = "done"
	JobStatusFailed        JobStatus = "failed"
	JobStatusStoppedBudget JobStatus = "stopped_budget"
	JobStatusCancelled     JobStatus = "cancelled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobType string

const (
	JobTypeDetectAttributes JobType = "detect_attributes"
	JobTypeGenerateListing  JobType = "generate_listing"
	JobTypeRegenerateField  JobType = "regenerate_field"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType `json:"job_type"`
	Valid   bool    `json:"valid"` // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type ListingStatus string

const (
	ListingStatusQueued        ListingStatus = "queued"
	ListingStatusGenerated     ListingStatus = "generated"
	ListingStatusFailed        ListingStatus = "failed"
	ListingStatusStoppedBudget ListingStatus = "stopped_budget"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus `json:"listing_status"`
	Valid         bool          `json:"valid"` // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type RegenerationStatus string

const (
	RegenerationStatusQueued        RegenerationStatus = "queued"
	RegenerationStatusApplied       RegenerationStatus = "applied"
	RegenerationStatusSuperseded    RegenerationStatus = "superseded"
	RegenerationStatusFailed        RegenerationStatus = "failed"
	RegenerationStatusStoppedBudget RegenerationStatus = "stopped_budget"
)

func (e *RegenerationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegenerationStatus(s)
	case string:
		*e = RegenerationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegenerationStatus: %T", src)
	}
	return nil
}

type NullRegenerationStatus struct {
	RegenerationStatus RegenerationStatus `json:"regeneration_status"`
	Valid              bool               `json:"valid"` // Valid is true if RegenerationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegenerationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegenerationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegenerationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegenerationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegenerationStatus), nil
}

type RuleStatus string

const (
	RuleStatusUnchecked RuleStatus = "unchecked"
	RuleStatusPassing   RuleStatus = "passing"
	RuleStatusFailing   RuleStatus = "failing"
)

func (e *RuleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleStatus(s)
	case string:
		*e = RuleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleStatus: %T", src)
	}
	return nil
}

type NullRuleStatus struct {
	RuleStatus RuleStatus `json:"rule_status"`
	Valid      bool       `json:"valid"` // Valid is true if RuleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleStatus), nil
}

type UserRole string

const (
	UserRoleSeller   UserRole = "seller"
	UserRoleReviewer UserRole = "reviewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

// One call through the AI gateway; the cost ledger. Serves US-00-011, US-00-012.
type AiCall struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The job that made the call; null for evals or after the job is purged.
	JobID pgtype.Int8 `json:"job_id"`
	// The product the call was for; null only for eval calls.
	ProductID pgtype.Int8 `json:"product_id"`
	// detect, generate, regenerate or eval_detect.
	Purpose AiCallPurpose `json:"purpose"`
	// Model id, such as claude-haiku-4-5.
	Model string `json:"model"`
	// Id of the prompt template rendered.
	PromptTemplateID string `json:"prompt_template_id"`
	// The rendered prompt sent.
	Prompt string `json:"prompt"`
	// reserved, succeeded, failed or possibly_charged.
	Status AiCallStatus `json:"status"`
	// Estimated cost reserved before the call, in millionths of a US dollar.
	ReservedMicroUsd int64 `json:"reserved_micro_usd"`
	// Actual cost reported, in millionths of a US dollar; null until known.
	CostMicroUsd pgtype.Int8 `json:"cost_micro_usd"`
	// Input tokens reported; null until known.
	InputTokens pgtype.Int4 `json:"input_tokens"`
	// Output tokens reported; null until known.
	OutputTokens pgtype.Int4 `json:"output_tokens"`
	// OpenRouter's generation id; null when not returned.
	ProviderGenerationID pgtype.Text `json:"provider_generation_id"`
	// Error returned; null on success.
	Error pgtype.Text `json:"error"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Spend per AI call under the single spend rule (data model section 4).
type AiCallSpend struct {
	ID            int64         `json:"id"`
	ProductID     pgtype.Int8   `json:"product_id"`
	Purpose       AiCallPurpose `json:"purpose"`
	Status        AiCallStatus  `json:"status"`
	SpendMicroUsd int64         `json:"spend_micro_usd"`
}

// A reviewer's approval of one listing version. Serves US-00-009, US-00-010.
type Approval struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The listing approved.
	ListingID int64 `json:"listing_id"`
	// Version approved; the listing counts as approved only while its version still equals this.
	ListingVersion int32 `json:"listing_version"`
	// The reviewer who approved.
	ApprovedBy int64 `json:"approved_by"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// A brand named in the upload CSV, with its voice note. Serves US-00-001, US-00-003.
type Brand struct {
	// Surrogate key; referenced by products.
	ID int64 `json:"id"`
	// Brand name as written in the CSV, unique ignoring case.
	Name string `json:"name"`
	// Short note on the brand's voice; null until the seller writes one.
	VoiceNote pgtype.Text `json:"voice_note"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// The single row holding the AI spend limit and blocked state. Serves US-00-012.
type Budget struct {
	// Always 1; the row the gateway locks.
	ID int16 `json:"id"`
	// Spend after which calls are refused, in millionths of a US dollar.
	LimitMicroUsd int64 `json:"limit_micro_usd"`
	// When the gateway first refused a call; null while not blocked.
	BlockedAt pgtype.Timestamptz `json:"blocked_at"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One start-up re-check after a channel rule change. Serves US-00-004, US-00-005.
type ConfigRecheck struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// Channel whose configuration changed.
	Channel string `json:"channel"`
	// Hash of the configuration now loaded.
	ConfigHash string `json:"config_hash"`
	// Listings validated again.
	ListingsRechecked int32 `json:"listings_rechecked"`
	// Approved listings that now fail and lost their approval.
	ApprovalsCleared int32 `json:"approvals_cleared"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One export run by a reviewer. Serves US-00-010.
type Export struct {
	// Surrogate key; the download URL names it.
	ID int64 `json:"id"`
	// The reviewer who exported.
	CreatedBy int64 `json:"created_by"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One channel's CSV within an export. Serves US-00-010.
type ExportFile struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The export the file belongs to.
	ExportID int64 `json:"export_id"`
	// Channel id from configuration.
	Channel string `json:"channel"`
	// Where the CSV is stored on the data disk.
	FilePath string `json:"file_path"`
	// Approved listings in the file.
	RowCount int32 `json:"row_count"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One start of generation by a seller. Serves US-00-003, US-00-012.
type GenerationRun struct {
	// Surrogate key; jobs and the progress view group by it.
	ID int64 `json:"id"`
	// Who started the run.
	StartedBy int64 `json:"started_by"`
	// True when the seller confirmed a neutral voice for brands with no voice note.
	NeutralVoiceConfirmed bool `json:"neutral_voice_confirmed"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One unit of background AI work claimed by the worker. Serves US-00-002, US-00-003, US-00-008, US-00-012.
type Job struct {
	// Surrogate key; logs carry it.
	ID int64 `json:"id"`
	// detect_attributes, generate_listing or regenerate_field.
	Type JobType `json:"type"`
	// Product, step and channel, or listing, field and request id for regenerations.
	DedupeKey string `json:"dedupe_key"`
	// queued, running, done, failed, stopped_budget or cancelled.
	Status JobStatus `json:"status"`
	// The run the job belongs to; null for regenerations.
	RunID pgtype.Int8 `json:"run_id"`
	// The product the work is for.
	ProductID int64 `json:"product_id"`
	// The listing written; null for detection.
	ListingID pgtype.Int8 `json:"listing_id"`
	// The request served; null unless a regeneration.
	RegenerationRequestID pgtype.Int8 `json:"regeneration_request_id"`
	// Attempts used, 0 to 3; a 429 does not use one.
	Attempts int16 `json:"attempts"`
	// Earliest time the job may be claimed.
	RunAfter pgtype.Timestamptz `json:"run_after"`
	// When the first attempt started; null until claimed.
	FirstAttemptAt pgtype.Timestamptz `json:"first_attempt_at"`
	// Attribute revision read when the prompt was built; null for detection.
	AttributesRevision pgtype.Int4 `json:"attributes_revision"`
	// Random token set on every claim; null unless running.
	ClaimToken pgtype.UUID `json:"claim_token"`
	// Worker process holding the claim; null unless running.
	ClaimedBy pgtype.Text `json:"claimed_by"`
	// When the claim expires; null unless running.
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	// Most recent error; null when none.
	LastError pgtype.Text `json:"last_error"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// When the job reached done, failed, stopped_budget or cancelled.
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// One product on one channel: text, version and rule status. Serves US-00-003, US-00-004, US-00-006 to US-00-010.
type Listing struct {
	// Surrogate key; the grid row and the URL of a listing.
	ID int64 `json:"id"`
	// The product described.
	ProductID int64 `json:"product_id"`
	// Channel id from configuration, such as amazon_style.
	Channel string `json:"channel"`
	// queued, generated, failed or stopped_budget.
	Status ListingStatus `json:"status"`
	// Why generation failed; null unless failed.
	FailureReason pgtype.Text `json:"failure_reason"`
	// 0 before generation; raised by every change to the text or the product's attributes.
	Version int32 `json:"version"`
	// Generated or edited title; null until generated.
	Title pgtype.Text `json:"title"`
	// Bullet point 1; null until generated.
	Bullet1 pgtype.Text `json:"bullet_1"`
	// Bullet point 2; null until generated.
	Bullet2 pgtype.Text `json:"bullet_2"`
	// Bullet point 3; null until generated.
	Bullet3 pgtype.Text `json:"bullet_3"`
	// Bullet point 4; null until generated.
	Bullet4 pgtype.Text `json:"bullet_4"`
	// Bullet point 5; null until generated.
	Bullet5 pgtype.Text `json:"bullet_5"`
	// Generated or edited description; null until generated.
	Description pgtype.Text `json:"description"`
	// unchecked, passing or failing for the current version.
	RuleStatus RuleStatus `json:"rule_status"`
	// Hash of the channel config the current status was checked against.
	RuleConfigHash pgtype.Text `json:"rule_config_hash"`
	// Whether the first generated version passed the rules; set once.
	FirstPassPassed pgtype.Bool `json:"first_pass_passed"`
	// Rule names the first version failed; set once with first_pass_passed.
	FirstPassFailedRules []string `json:"first_pass_failed_rules"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One SKU from the CSV. Serves US-00-001, US-00-002, US-00-003, US-00-011.
type Product struct {
	// Surrogate key; referenced by images, attributes, listings, jobs and AI calls.
	ID int64 `json:"id"`
	// Seller's product code, unique ignoring case across Catalift.
	Sku string `json:"sku"`
	// The product's brand.
	BrandID int64 `json:"brand_id"`
	// The upload that created the product.
	UploadID int64 `json:"upload_id"`
	// Category from the CSV.
	Category string `json:"category"`
	// Price in minor units of currency (paise).
	PriceMinor int64 `json:"price_minor"`
	// ISO 4217 code of price_minor.
	Currency string `json:"currency"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// The five detected attributes of a product, owned by listings. Serves US-00-002, US-00-007.
type ProductAttribute struct {
	// The product described; one row each.
	ProductID int64 `json:"product_id"`
	// pending, done, failed or stopped_budget.
	DetectionStatus DetectionStatus `json:"detection_status"`
	// Raised by every detection result and every reviewer correction.
	Revision int32 `json:"revision"`
	// Detected or corrected colour; 'unknown' when unclear; null until done.
	Colour pgtype.Text `json:"colour"`
	// Detected or corrected pattern; null until done.
	Pattern pgtype.Text `json:"pattern"`
	// Detected or corrected sleeve; null until done.
	Sleeve pgtype.Text `json:"sleeve"`
	// Detected or corrected neckline; null until done.
	Neckline pgtype.Text `json:"neckline"`
	// Detected or corrected fit; null until done.
	Fit pgtype.Text `json:"fit"`
	// Why detection failed; null unless failed.
	DetectionError pgtype.Text `json:"detection_error"`
	// Reviewer who last corrected an attribute; null while only detected.
	CorrectedBy pgtype.Int8 `json:"corrected_by"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// A photo attached to a product, with its detection copy. Serves US-00-001, US-00-002.
type ProductImage struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The product the image belongs to.
	ProductID int64 `json:"product_id"`
	// Order among the product's images; 1 drives detection.
	Position int16 `json:"position"`
	// File name as uploaded.
	OriginalFileName string `json:"original_file_name"`
	// Where the original is stored on the data disk, under a generated name.
	OriginalPath string `json:"original_path"`
	// Where the copy scaled to at most 1024 px on its long side is stored.
	DetectionPath string `json:"detection_path"`
	// Sniffed image type.
	ContentType string `json:"content_type"`
	// Size of the original in bytes.
	ByteSize int32 `json:"byte_size"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// A reviewer's request to rewrite one field. Serves US-00-008.
type RegenerationRequest struct {
	// Surrogate key; the request id in the regenerate job key.
	ID int64 `json:"id"`
	// The listing to change.
	ListingID int64 `json:"listing_id"`
	// title, bullet_1 to bullet_5, or description.
	Field string `json:"field"`
	// Reviewer's free-text instruction.
	Instruction string `json:"instruction"`
	// The field's value when the request was made.
	BaseValue string `json:"base_value"`
	// queued, applied, superseded, failed or stopped_budget.
	Status RegenerationStatus `json:"status"`
	// The reviewer who asked.
	RequestedBy int64 `json:"requested_by"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One rule failure of one listing version. Serves US-00-004, US-00-007.
type RuleResult struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The listing that failed.
	ListingID int64 `json:"listing_id"`
	// Version the rule was checked against.
	ListingVersion int32 `json:"listing_version"`
	// Rule name, such as title_max_length.
	Rule string `json:"rule"`
	// Field the failure is in, such as title or bullet_3.
	Field string `json:"field"`
	// Detail shown to the reviewer: limit and length, the word, or the missing attribute.
	Message string `json:"message"`
	// Hash of the channel config used.
	ConfigHash string `json:"config_hash"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchemaProbe struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// A signed-in browser session. Serves ADR-0006.
type Session struct {
	// SHA-256 of the session cookie token; the token itself is never stored.
	TokenHash string `json:"token_hash"`
	// The signed-in user.
	UserID int64 `json:"user_id"`
	// Hash of the CSRF token every state-changing request must send.
	CsrfTokenHash string `json:"csrf_token_hash"`
	// When the session stops being accepted.
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One CSV upload by a seller. Serves US-00-001.
type Upload struct {
	// Surrogate key; the upload images are attached to.
	ID int64 `json:"id"`
	// The seller who uploaded.
	UploadedBy int64 `json:"uploaded_by"`
	// Name of the uploaded CSV file.
	FileName string `json:"file_name"`
	// Data rows in the file.
	RowsTotal int32 `json:"rows_total"`
	// Rows that became products.
	RowsAccepted int32 `json:"rows_accepted"`
	// Rows refused, each listed in upload_row_errors.
	RowsRejected int32 `json:"rows_rejected"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// A CSV row the upload refused, with its reason. Serves US-00-001.
type UploadRowError struct {
	// Surrogate key.
	ID int64 `json:"id"`
	// The upload the row came from.
	UploadID int64 `json:"upload_id"`
	// Line number in the CSV file, the header being line 1.
	RowNumber int32 `json:"row_number"`
	// SKU on the refused row; null when the row had none.
	Sku pgtype.Text `json:"sku"`
	// Why the row was refused, as shown to the seller.
	Reason string `json:"reason"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// A seeded person who signs in as a seller or a reviewer. Serves ADR-0006, US-00-009, US-00-010.
type User struct {
	// Surrogate key; referenced by sessions, uploads, runs, approvals and requests.
	ID int64 `json:"id"`
	// Sign-in address, unique ignoring case. [personal data]
	Email string `json:"email"`
	// seller or reviewer; checked by the API on every route.
	Role UserRole `json:"role"`
	// Password hash (argon2id or bcrypt, chosen in the LLD), never the password. [personal data]
	PasswordHash string `json:"password_hash"`
	// When the row was written.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last change to this row, set by the repository on every update.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
